dist: xenial

language: node_js

node_js:
- lts/*

cache:
  directories:
  - "$HOME/.npm"

git:
  depth: 3

addons:
  ssh_known_hosts: "$SSH_HOST"

before_install:
- openssl aes-256-cbc -K $encrypted_1a0eab816a79_key -iv $encrypted_1a0eab816a79_iv -in travis.enc -out ~\/.ssh/travis -d

before_script:
  - chmod 600 ./deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add ./deploy_key

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: bash script/deploy.sh
